//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTTS {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenTTS.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;角色&quot;:&quot;Girl&quot;,
        ///        &quot;描述&quot;:&quot;声音模仿女孩。&quot;
        ///    },{
        ///        &quot;角色&quot;:&quot;Boy&quot;,
        ///        &quot;描述&quot;:&quot;声音模仿男孩。&quot;
        ///    },{
        ///        &quot;角色&quot;:&quot;YoungAdultFemale&quot;,
        ///        &quot;描述&quot;:&quot;声音模仿年轻的成年女性。&quot;
        ///    },{
        ///        &quot;角色&quot;:&quot;YoungAdultMale&quot;,
        ///        &quot;描述&quot;:&quot;声音模仿年轻的成年男性。&quot;
        ///    },{
        ///        &quot;角色&quot;:&quot;OlderAdultFemale&quot;,
        ///        &quot;描述&quot;:&quot;声音模仿年长的成年女性。&quot;
        ///    },{
        ///        &quot;角色&quot;:&quot;OlderAdultMale&quot;,
        ///        &quot;描述&quot;:&quot;声音模仿年长的成年男性。&quot;
        ///    },{
        ///        &quot;角色&quot;:&quot;SeniorFemale&quot;,
        ///        &quot;描述&quot;:&quot;声音模仿年老女性。&quot;
        ///    },{
        ///        &quot;角色&quot;:&quot;SeniorMale&quot;,
        ///        &quot;描述&quot;:&quot;声音 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AllRoles {
            get {
                return ResourceManager.GetString("AllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;语气&quot;:&quot;advertisement_upbeat&quot;,
        ///        &quot;描述&quot;:&quot;用兴奋和精力充沛的语气推广产品或服务。&quot;
        ///    },{
        ///        &quot;语气&quot;:&quot;affectionate&quot;,
        ///        &quot;描述&quot;:&quot;以较高的音调和音量表达温暖而亲切的语气。 说话者处于吸引听众注意力的状态。 说话者的个性往往是讨喜的。&quot;
        ///    },{
        ///        &quot;语气&quot;:&quot;angry&quot;,
        ///        &quot;描述&quot;:&quot;表达生气和厌恶的语气。&quot;
        ///    },{
        ///        &quot;语气&quot;:&quot;assistant&quot;,
        ///        &quot;描述&quot;:&quot;数字助理用的是热情而轻松的语气。&quot;
        ///    },{
        ///        &quot;语气&quot;:&quot;calm&quot;,
        ///        &quot;描述&quot;:&quot;以沉着冷静的态度说话。 语气、音调和韵律与其他语音类型相比要统一得多。&quot;
        ///    },{
        ///        &quot;语气&quot;:&quot;chat&quot;,
        ///        &quot;描述&quot;:&quot;表达轻松随意的语气。&quot;
        ///    },{
        ///        &quot;语气&quot;:&quot;cheerful&quot;,
        ///        &quot;描述&quot;:&quot;表达 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string AllSpeachStyles {
            get {
                return ResourceManager.GetString("AllSpeachStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///  {
        ///    &quot;名字&quot;: &quot;小晗&quot;,
        ///    &quot;编码&quot;: &quot;zh-CN-XiaohanNeural&quot;,
        ///    &quot;性别&quot;: &quot;女&quot;,
        ///    &quot;语言&quot;: &quot;zh_CN&quot;,
        ///    &quot;语气&quot;: null,
        ///    &quot;角色&quot;: null,
        ///    &quot;支持的角色&quot;: null,
        ///
        ///    &quot;支持的语气&quot;: [
        ///      {
        ///        &quot;语气&quot;: &quot;cheerful&quot;,
        ///        &quot;描述&quot;: &quot;以较高的音调和音量表达欢快、热情的语气&quot;
        ///      },
        ///      {
        ///        &quot;语气&quot;: &quot;sad&quot;,
        ///        &quot;描述&quot;: &quot;以较高的音调、较低的强度和较低的音量表达悲伤的语气。 这种情绪的常见特征是说话时呜咽或哭泣。&quot;
        ///      },
        ///      {
        ///        &quot;语气&quot;: &quot;angry&quot;,
        ///        &quot;描述&quot;: &quot;以较低的音调、较高的强度和较高的音量来表达恼怒的语气。 说话者处于愤怒、生气和被冒犯的状态。&quot;
        ///      },
        ///      {
        ///        &quot;语气&quot;: &quot;fearful&quot;,
        ///        &quot;描述&quot;: &quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string SpeechResources {
            get {
                return ResourceManager.GetString("SpeechResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;speak version=&quot;1.0&quot;
        ///    xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot;
        ///    xmlns:mstts=&quot;https://www.w3.org/2001/mstts&quot; xml:lang=&quot;@Param1&quot;&gt;
        ///    &lt;voice name=&quot;@Param2&quot; rate=&quot;@Param3&quot;&gt;
        ///        &lt;mstts:express-as style=&quot;@Param4&quot; styledegree=&quot;@Param5&quot;&gt;
        ///			@Param6
        ///		&lt;/mstts:express-as&gt;
        ///    &lt;/voice&gt;
        ///&lt;/speak&gt; 的本地化字符串。
        /// </summary>
        public static string ssml {
            get {
                return ResourceManager.GetString("ssml", resourceCulture);
            }
        }
    }
}
